### PR TITLE
Blockly function block

### PR DESCRIPTION
**Pull request by jessica-norris**
This PR changes the procedure blocks that are created during flyout for the procedures category. We suppress all the mutator blocks and I've provided instead a simple block that takes no parameters and returns no return value. This PR also fixes some bugs in the python generator for procedures.

PR in app/ with the same branch name relies upon this PR.

### CODE REVIEW

**Review by timdawborn — APPROVED** [review]
It looks like you accidentally committed the files changed by compilation. Can you remove all of the `msg/js/*.js` files from this PR since any changes here will continuously clash with upstream if we change them?

LGTM otherwise.

**Comment by jessica-norris** [comment]
How do I remove them from the commit / PR without removing them from the index? (I know how to do `git rm` but it looks like these files are being tracked, but that I shouldn't have committed them).

**Comment by timdawborn** [comment]
```
$ git checkout 2f3540ffba2272ccb53515d9d68d59c876d957e5 -- msg/js
```

`2f3540ffba2272ccb53515d9d68d59c876d957e5` being `HEAD` of `develop-grok` :)

**Comment by jessica-norris** [comment]
Okay, I think I've got them all now. :)

**Review by timdawborn — APPROVED** [review]

**Pull request merged**
